# Orange Pi Zero / WuKong Pi H3 Zero 512MB development image.
BOARD=orangepizero
BRANCH=current
RELEASE=trixie
BUILD_MINIMAL=yes
BUILD_DESKTOP=no
KERNEL_CONFIGURE=no
EXPERT=yes
NETWORKING_STACK=network-manager
HOST=carlife-h3
COMPRESS_OUTPUTIMAGE=sha,xz
EXTRA_ROOTFS_MIB_SIZE=512
ENABLE_EXTENSIONS=carlife-h3-tools
